#ifndef APPLICATION_ID_DEFINITIONS_H__
#define APPLICATION_ID_DEFINITIONS_H__

// Vectorworks
#define MELANGE_APPLICATION_ID_VECTORWORKS 310003000

// Allplan
#define MELANGE_APPLICATION_ID_ALLPLAN 1026284

// ArchiCAD
#define MELANGE_APPLICATION_ID_ARCHICAD_18 1032064; // ArchiCAD 18 and above
#define MELANGE_APPLICATION_ID_ARCHICAD 1026292 // ArchiCAD 17 and before

#endif // APPLICATION_ID_DEFINITIONS_H__